# Generated by Django 5.1.3 on 2025-08-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='codigo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
