# Generated by Django 5.1.3 on 2025-09-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_incomes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_outcomes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='agua.cashbox')),
            ],
            options={
                'unique_together': {('cashbox', 'date')},
            },
        ),
    ]
