# Generated by Django 5.1.3 on 2025-08-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_category_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.CharField(default=1, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo')], max_length=50),
        ),
    ]
