# Generated by Django 5.1.3 on 2025-09-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_dailycashreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lote',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mz',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nro',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
