# Generated by Django 5.1.3 on 2025-10-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_cashoutflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashconcept',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
