# Generated by Django 5.1.3 on 2025-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_invoice_code_alter_invoice_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
