# Generated by Django 5.1.3 on 2025-10-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0004_cashconcept_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agua.cashconcept')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_concepts', to='agua.invoice')),
            ],
        ),
    ]
