# Generated by Django 5.1.3 on 2025-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identity_document_type',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
