# Generated by Django 5.1.3 on 2025-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_invoiceconcept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='via',
            name='codigo',
            field=models.CharField(editable=False, max_length=2, unique=True),
        ),
    ]
