# Generated by Django 5.1.3 on 2025-10-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0006_alter_via_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calle',
            name='codigo',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
    ]
