# Generated by Django 5.1.3 on 2025-10-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_alter_calle_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name_optional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='number_optional',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
