# Generated by Django 5.1.3 on 2025-08-21 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_alter_customer_identity_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='calle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agua.calle'),
        ),
    ]
