# Generated by Django 5.1.3 on 2025-10-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0008_invoice_name_optional_invoice_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=15),
        ),
    ]
