# Generated by Django 5.1.3 on 2025-08-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0008_customer_calle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
    ]
