# Generated by Django 5.1.3 on 2025-10-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0009_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashconcept',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
