# Generated by Django 5.1.3 on 2025-08-21 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0009_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agua.zona'),
        ),
    ]
