# Generated by Django 5.1.3 on 2025-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0010_customer_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='codigo',
            field=models.CharField(max_length=4),
        ),
    ]
