# Generated by Django 5.1.3 on 2025-08-22 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0011_alter_zona_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='agua.customer')),
                ('reading', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt', to='agua.reading')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('customer', 'period', 'reading')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoicereading',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoicereading',
            name='debt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='agua.debt'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoicereading',
            unique_together={('invoice', 'debt')},
        ),
        migrations.RemoveField(
            model_name='invoicereading',
            name='reading',
        ),
    ]
