# Generated by Django 5.1.3 on 2025-08-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0012_debt_alter_invoicereading_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debt',
            unique_together=set(),
        ),
    ]
