# Generated by Django 5.1.3 on 2025-08-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0013_alter_debt_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceReading',
            new_name='InvoiceDebt',
        ),
    ]
