# Generated by Django 5.1.3 on 2025-08-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0014_rename_invoicereading_invoicedebt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedebt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_debts', to='agua.invoice'),
        ),
    ]
