# Generated by Django 5.1.3 on 2025-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0015_alter_invoicedebt_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='max_m3',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='min_m3',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='price_per_m3',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
