# Generated by Django 5.1.3 on 2025-08-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0016_category_description_category_max_m3_category_min_m3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='codigo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
