# Generated by Django 5.1.3 on 2025-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0017_alter_category_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='max_m3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='min_m3',
        ),
        migrations.AddField(
            model_name='category',
            name='consumo_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='consumo_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
