# Generated by Django 5.1.3 on 2025-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0018_remove_category_max_m3_remove_category_min_m3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extra_price_water',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
