# Generated by Django 5.1.3 on 2025-08-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0019_category_extra_price_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price_per_m3',
        ),
    ]
