# Generated by Django 5.1.3 on 2025-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0020_remove_category_price_per_m3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='extra_price_water',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
