# Generated by Django 5.1.3 on 2025-08-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0021_alter_category_extra_price_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='consumo_max',
        ),
        migrations.RemoveField(
            model_name='category',
            name='consumo_min',
        ),
        migrations.AddField(
            model_name='category',
            name='max_consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
