# Generated by Django 5.1.3 on 2025-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0022_remove_category_consumo_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='extra_price_water',
        ),
        migrations.AddField(
            model_name='category',
            name='extra_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
