# Generated by Django 5.1.3 on 2025-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0023_remove_category_extra_price_water_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
