# Generated by Django 5.1.3 on 2025-09-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0024_category_min_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
