# Generated by Django 5.1.3 on 2025-09-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0025_category_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
