# Generated by Django 5.1.3 on 2025-09-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0026_delete_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Anulada')], default='active', max_length=20),
        ),
    ]
