# Generated by Django 5.1.3 on 2025-09-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0028_readinggeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='date_of_cute',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='date_of_due',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='date_of_issue',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='readinggeneration',
            name='date_of_cute',
            field=models.DateField(default='2025-03-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinggeneration',
            name='date_of_due',
            field=models.DateField(default='2025-03-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinggeneration',
            name='date_of_issue',
            field=models.DateField(default='2025-03-12'),
            preserve_default=False,
        ),
    ]
