# Generated by Django 5.1.3 on 2025-09-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0029_reading_date_of_cute_reading_date_of_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedebt',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
