# Generated by Django 5.1.3 on 2025-09-16 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0031_remove_invoice_method_cashbox_invoicepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso'), ('deposit', 'Depósito bancario')], max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='cashmovement',
            old_name='amount',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='cashmovement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cashmovement',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='cashmovement',
            name='type',
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='invoice_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='agua.invoicepayment'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='concept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='agua.cashconcept'),
            preserve_default=False,
        ),
    ]
