# Generated by Django 5.1.3 on 2025-09-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0032_cashconcept_rename_amount_cashmovement_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashconcept',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cashconcept',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
