# Generated by Django 5.1.3 on 2025-09-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0033_alter_cashconcept_name_alter_cashconcept_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='total_fixed_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
