# Generated by Django 5.1.3 on 2025-09-17 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0034_reading_total_fixed_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agua.cashconcept')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='agua.debt')),
            ],
        ),
    ]
