# Generated by Django 5.1.3 on 2025-09-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0035_debtdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashconcept',
            name='code',
            field=models.CharField(default=1, max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
