# Generated by Django 5.1.3 on 2025-09-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0036_cashconcept_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='has_meter',
            field=models.BooleanField(default=False),
        ),
    ]
