# Generated by Django 5.1.3 on 2025-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
