# Generated by Django 5.1.3 on 2025-10-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_globalpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user.module'),
        ),
        migrations.DeleteModel(
            name='GlobalPermission',
        ),
    ]
