# Generated by Django 5.1.3 on 2025-10-17 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userpermission_actions_alter_userpermission_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='actions',
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='user.module'),
        ),
        migrations.CreateModel(
            name='GlobalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_actions', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
